// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from "./client";
import { client } from "./client.gen";
import type {
  ApprovePlanData,
  ApprovePlanErrors,
  ApprovePlanResponses,
  CreateSessionData,
  CreateSessionErrors,
  CreateSessionResponses,
  GetActivityData,
  GetActivityErrors,
  GetActivityResponses,
  GetSessionData,
  GetSessionErrors,
  GetSessionResponses,
  GetSourceData,
  GetSourceErrors,
  GetSourceResponses,
  ListActivitiesData,
  ListActivitiesErrors,
  ListActivitiesResponses,
  ListSessionsData,
  ListSessionsErrors,
  ListSessionsResponses,
  ListSourcesData,
  ListSourcesErrors,
  ListSourcesResponses,
  SendMessageData,
  SendMessageErrors,
  SendMessageResponses,
} from "./types.gen";

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
> = Options2<TData, ThrowOnError> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

/**
 * Approves a plan in a session.
 */
export const approvePlan = <ThrowOnError extends boolean = false>(
  options: Options<ApprovePlanData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    ApprovePlanResponses,
    ApprovePlanErrors,
    ThrowOnError
  >({
    security: [{ name: "X-Goog-Api-Key", type: "apiKey" }],
    url: "/sessions/{session}:approvePlan",
    ...options,
  });

/**
 * Lists all sessions.
 */
export const listSessions = <ThrowOnError extends boolean = false>(
  options?: Options<ListSessionsData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    ListSessionsResponses,
    ListSessionsErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [{ name: "X-Goog-Api-Key", type: "apiKey" }],
    url: "/sessions",
    ...options,
  });

/**
 * Creates a new session.
 */
export const createSession = <ThrowOnError extends boolean = false>(
  options: Options<CreateSessionData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    CreateSessionResponses,
    CreateSessionErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [{ name: "X-Goog-Api-Key", type: "apiKey" }],
    url: "/sessions",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Retrieves a specific session.
 */
export const getSession = <ThrowOnError extends boolean = false>(
  options: Options<GetSessionData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetSessionResponses,
    GetSessionErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [{ name: "X-Goog-Api-Key", type: "apiKey" }],
    url: "/sessions/{name}",
    ...options,
  });

/**
 * Sends a message from the user to a session.
 */
export const sendMessage = <ThrowOnError extends boolean = false>(
  options: Options<SendMessageData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    SendMessageResponses,
    SendMessageErrors,
    ThrowOnError
  >({
    security: [{ name: "X-Goog-Api-Key", type: "apiKey" }],
    url: "/sessions/{session}:sendMessage",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Gets a single activity.
 */
export const getActivity = <ThrowOnError extends boolean = false>(
  options: Options<GetActivityData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetActivityResponses,
    GetActivityErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [{ name: "X-Goog-Api-Key", type: "apiKey" }],
    url: "/sessions/{session}/activities/{activity}",
    ...options,
  });

/**
 * Lists activities for a session.
 */
export const listActivities = <ThrowOnError extends boolean = false>(
  options: Options<ListActivitiesData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    ListActivitiesResponses,
    ListActivitiesErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [{ name: "X-Goog-Api-Key", type: "apiKey" }],
    url: "/sessions/{session}/activities",
    ...options,
  });

/**
 * Gets a single source.
 */
export const getSource = <ThrowOnError extends boolean = false>(
  options: Options<GetSourceData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetSourceResponses,
    GetSourceErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [{ name: "X-Goog-Api-Key", type: "apiKey" }],
    url: "/sources/{name}",
    ...options,
  });

/**
 * Lists sources.
 */
export const listSources = <ThrowOnError extends boolean = false>(
  options?: Options<ListSourcesData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    ListSourcesResponses,
    ListSourcesErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [{ name: "X-Goog-Api-Key", type: "apiKey" }],
    url: "/sources",
    ...options,
  });
