// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseURL: "https://jules.googleapis.com/v1alpha" | (string & {});
};

/**
 * A continuous unit of work within a specific context, similar to a chat session. A session is
 * initiated with a prompt and a source.
 *
 */
export type Session = {
  /**
   * Output only. Identifier. The full resource name (e.g., "sessions/{session}").
   *
   */
  name?: string;
  /**
   * Output only. The id of the session. This is the same as the "{session}" part of the
   * resource name (e.g., "sessions/{session}").
   *
   */
  id?: string;
  /**
   * Required. The prompt to start the session with.
   *
   */
  prompt: string;
  /**
   * Required. The source to use in this session, with additional context.
   *
   */
  sourceContext: SourceContext;
  /**
   * Optional. If not provided, the system will generate one.
   *
   */
  title?: string;
  /**
   * Optional. Input only. If true, plans the agent generates will require explicit plan
   * approval before the agent starts working. If not set, plans will be auto-approved.
   *
   */
  requirePlanApproval?: boolean;
  /**
   * Optional. Input only. The automation mode of the session. If not set, the default
   * automation mode will be used.
   *
   */
  automationMode?: "AUTOMATION_MODE_UNSPECIFIED" | "AUTO_CREATE_PR";
  /**
   * Output only. The time the session was created.
   * Uses RFC 3339, where generated output will always be Z-normalized and use 0, 3, 6 or 9
   * fractional digits. Offsets other than "Z" are also accepted. Examples:
   * "2014-10-02T15:01:23Z", "2014-10-02T15:01:23.045123456Z" or "2014-10-02T15:01:23+05:30".
   *
   */
  createTime?: string;
  /**
   * Output only. The time the session was last updated.
   * Uses RFC 3339, where generated output will always be Z-normalized and use 0, 3, 6 or 9
   * fractional digits. Offsets other than "Z" are also accepted. Examples:
   * "2014-10-02T15:01:23Z", "2014-10-02T15:01:23.045123456Z" or "2014-10-02T15:01:23+05:30".
   *
   */
  updateTime?: string;
  /**
   * Output only. The state of the session.
   *
   */
  state?:
    | "STATE_UNSPECIFIED,"
    | "QUEUED,"
    | "PLANNING,"
    | "AWAITING_PLAN_APPROVAL,"
    | "AWAITING_USER_FEEDBACK,"
    | "IN_PROGRESS,"
    | "PAUSED,"
    | "FAILED,"
    | "COMPLETED,";
  /**
   * Output only. The URL of the session to view the session in the Jules web app.
   *
   */
  url?: string;
  /**
   * Output only. The outputs of the session, if any.
   *
   */
  outputs?: Array<SessionOutput>;
};

export type SourceContext = {
  githubRepoContext: GithubRepoContext;
} & {
  /**
   * Required. The name of the source this context is for. To get the list of sources,
   * use the ListSources API. Format: sources/{source}
   *
   */
  source?: string;
};

/**
 * Context to use a GitHubRepo in a session.
 *
 */
export type GithubRepoContext = {
  /**
   * Required. The name of the branch to start the session from.
   *
   */
  startingBranch: string;
};

/**
 * A pull request created by the session, if applicable.
 *
 */
export type SessionOutput = {
  pullRequest: PullRequest;
};

/**
 * A pull request.
 *
 */
export type PullRequest = {
  /**
   * The URL of the pull request.
   *
   */
  url?: string;
  /**
   * The title of the pull request.
   *
   */
  title?: string;
  /**
   * The description of the pull request.
   *
   */
  description?: string;
};

export type Activity = (
  | {
      agentMessaged?: AgentMessaged;
    }
  | {
      userMessaged?: UserMessaged;
    }
  | {
      planGenerated?: PlanGenerated;
    }
  | {
      planApproved?: PlanApproved;
    }
  | {
      progressUpdated?: ProgressUpdated;
    }
  | {
      sessionCompleted?: SessionCompleted;
    }
  | {
      sessionFailed?: SessionFailed;
    }
) & {
  /**
   * Identifier. The full resource name (e.g.,
   * "sessions/{session}/activities/{activity}").
   *
   */
  name?: string;
  /**
   * Output only. The id of the activity. This is the same as the "{activity}" part of
   * the resource name (e.g., "sessions/{session}/activities/{activity}").
   *
   */
  id?: string;
  /**
   * Output only. A description of this activity.
   *
   */
  description?: string;
  /**
   * Output only. The time at which this activity was created.
   * Uses RFC 3339, where generated output will always be Z-normalized and use 0, 3, 6 or
   * 9 fractional digits. Offsets other than "Z" are also accepted. Examples:
   * "2014-10-02T15:01:23Z", "2014-10-02T15:01:23.045123456Z" or
   * "2014-10-02T15:01:23+05:30".
   *
   */
  createTime?: string;
  /**
   * The entity that this activity originated from (e.g. "user", "agent", "system").
   *
   */
  originator?: string;
  /**
   * Output only. The artifacts produced by this activity.
   *
   */
  artifacts?: Array<Artifact>;
};

/**
 * The agent posted a message.
 *
 */
export type AgentMessaged = {
  /**
   * The message the agent posted.
   *
   */
  agentMessage: string;
};

/**
 * The user posted a message.
 *
 */
export type UserMessaged = {
  /**
   * The message the user posted.
   *
   */
  userMessage?: string;
};

/**
 * A plan was generated.
 *
 */
export type PlanGenerated = {
  /**
   * The plan that was generated.
   *
   */
  plan?: Plan;
};

/**
 * A plan is a sequence of steps that the agent will take to complete the task.
 *
 */
export type Plan = {
  /**
   * Output only. ID for this plan; unique within a session.
   *
   */
  id?: string;
  /**
   * Output only. The steps in the plan.
   *
   */
  steps?: Array<PlanStep>;
  /**
   * Output only. Time when the plan was created.
   * Uses RFC 3339, where generated output will always be Z-normalized and use 0, 3, 6 or 9
   * fractional digits. Offsets other than "Z" are also accepted. Examples:
   * "2014-10-02T15:01:23Z", "2014-10-02T15:01:23.045123456Z" or "2014-10-02T15:01:23+05:30".
   *
   */
  createTime?: string;
};

/**
 * A step in a plan.
 *
 */
export type PlanStep = {
  /**
   * Output only. ID for this step; unique within a plan.
   *
   */
  id?: string;
  /**
   * Output only. The title of the step.
   *
   */
  title?: string;
  /**
   * Output only. The description of the step.
   *
   */
  description?: string;
  /**
   * Output only. 0-based index into the plan.steps.
   *
   */
  index?: number;
};

/**
 * A plan was approved.
 *
 */
export type PlanApproved = {
  /**
   * The ID of the plan that was approved.
   *
   */
  planId?: string;
};

/**
 * There was a progress update.
 *
 */
export type ProgressUpdated = {
  /**
   * The title of the progress update.
   *
   */
  title?: string;
  /**
   * The description of the progress update.
   *
   */
  description?: string;
};

/**
 * The session was completed.
 * This type has no fields.
 *
 */
export type SessionCompleted = {
  [key: string]: unknown;
};

/**
 * The session failed.
 *
 */
export type SessionFailed = {
  /**
   * The reason the session failed.
   *
   */
  reason?: string;
};

export type Artifact =
  | {
      changeSet?: ChangeSet;
    }
  | {
      media?: Media;
    }
  | {
      bashOutput?: BashOutput;
    };

export type ChangeSet = {
  gitPatch?: GitPatch;
} & {
  /**
   * The name of the source this change set applies to. Format: sources/{source}
   *
   */
  source?: string;
};

/**
 * A patch in Git format.
 *
 */
export type GitPatch = {
  /**
   * The patch in unidiff format.
   *
   */
  unidiffPatch?: string;
  /**
   * The base commit id of the patch. This is the id of the commit that the patch should be
   * applied to.
   *
   */
  baseCommitId?: string;
  /**
   * A suggested commit message for the patch, if one is generated.
   *
   */
  suggestedCommitMessage?: string;
};

/**
 * A media output.
 *
 */
export type Media = {
  /**
   * The media data.
   * A base64-encoded string.
   *
   */
  data?: string;
  /**
   * The media mime type.
   *
   */
  mimeType?: string;
};

/**
 * A bash output.
 *
 */
export type BashOutput = {
  /**
   * The bash command.
   *
   */
  command?: string;
  /**
   * The bash output. Includes both stdout and stderr.
   *
   */
  output?: string;
  /**
   * The bash exit code.
   *
   */
  exitCode?: string;
};

export type Source = {
  githubRepo?: GitHubRepo;
} & {
  /**
   * Identifier. The full resource name (e.g., "sources/{source}").
   *
   */
  name?: string;
  /**
   * Output only. The id of the source. This is the same as the "{source}" part of the
   * resource name (e.g., "sources/{source}").
   *
   */
  id?: string;
};

/**
 * A GitHub repo.
 *
 */
export type GitHubRepo = {
  owner?: string;
  repo?: string;
  isPrivate?: boolean;
  /**
   * The default branch for this repo.
   *
   */
  defaultBranch?: GitHubBranch;
  /**
   * The list of active branches for this repo.
   *
   */
  branches?: Array<GitHubBranch>;
};

/**
 * A GitHub branch.
 *
 */
export type GitHubBranch = {
  /**
   * The name of the GitHub branch.
   *
   */
  displayName?: string;
};

export type ApprovePlanData = {
  body?: never;
  path: {
    /**
     * Required. The resource name of the session to approve the plan in. Format:
     * sessions/{session} It takes the form sessions/{session}.
     *
     */
    session: string;
  };
  query?: never;
  url: "/sessions/{session}:approvePlan";
};

export type ApprovePlanErrors = {
  /**
   * Invalid argument.
   *
   */
  400: unknown;
  /**
   * Permission denied.
   *
   */
  403: unknown;
  /**
   * Session not found.
   *
   */
  404: unknown;
};

export type ApprovePlanResponses = {
  /**
   * If successful, the response body is empty.
   *
   */
  200: unknown;
};

export type ListSessionsData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Optional. The number of sessions to return. Must be between 1 and 100, inclusive. If
     * unset, defaults to 30. If set to greater than 100, it will be coerced to 100.
     *
     */
    pageSize?: number;
    /**
     * Optional. A page token, received from a previous sessions.list call.
     *
     */
    pageToken?: string;
  };
  url: "/sessions";
};

export type ListSessionsErrors = {
  /**
   * Invalid argument.
   *
   */
  400: unknown;
  /**
   * Permission denied.
   *
   */
  403: unknown;
};

export type ListSessionsResponses = {
  /**
   * Response message for sessions.list.
   *
   */
  200: {
    /**
     * The sessions from the specified request.
     *
     */
    sessions?: Array<Session>;
    /**
     * A token, which can be sent as pageToken to retrieve the next page. If this
     * field is omitted, there are no subsequent pages.
     *
     */
    nextPageToken?: string;
  };
};

export type ListSessionsResponse =
  ListSessionsResponses[keyof ListSessionsResponses];

export type CreateSessionData = {
  /**
   * The request body contains an instance of Session.
   *
   */
  body: Session;
  path?: never;
  query?: never;
  url: "/sessions";
};

export type CreateSessionErrors = {
  /**
   * Invalid argument.
   *
   */
  400: unknown;
  /**
   * Permission denied.
   *
   */
  403: unknown;
};

export type CreateSessionResponses = {
  /**
   * If successful, the response body contains a newly created instance of Session.
   *
   */
  200: Session;
};

export type CreateSessionResponse =
  CreateSessionResponses[keyof CreateSessionResponses];

export type GetSessionData = {
  body?: never;
  path: {
    /**
     * The resource name of the session to retrieve.
     * Format: sessions/{session}
     *
     */
    name: string;
  };
  query?: never;
  url: "/sessions/{name}";
};

export type GetSessionErrors = {
  /**
   * Invalid argument.
   *
   */
  400: unknown;
  /**
   * Permission denied.
   *
   */
  403: unknown;
  /**
   * Session Not Found
   *
   */
  404: unknown;
};

export type GetSessionResponses = {
  /**
   * If successful, the response body contains an instance of Session.
   *
   */
  200: Session;
};

export type GetSessionResponse = GetSessionResponses[keyof GetSessionResponses];

export type SendMessageData = {
  /**
   * The request body contains data with the following structure:
   *
   */
  body: {
    /**
     * Required. The user prompt to send to the session
     *
     */
    prompt: string;
  };
  path: {
    /**
     * Required. The resource name of the session to post the message to. Format:
     * sessions/{session} It takes the form sessions/{session}.
     *
     */
    session: string;
  };
  query?: never;
  url: "/sessions/{session}:sendMessage";
};

export type SendMessageErrors = {
  /**
   * Invalid argument.
   *
   */
  400: unknown;
  /**
   * Permission denied.
   *
   */
  403: unknown;
  /**
   * Session Not Found
   *
   */
  404: unknown;
};

export type SendMessageResponses = {
  /**
   * If successful, the response body is empty.
   *
   */
  200: unknown;
};

export type GetActivityData = {
  body?: never;
  path: {
    /**
     * Required. The resource name of the activity to retrieve. Format:
     * sessions/{session}/activities/{activity} It takes the form
     * sessions/{session}/activities/{activities}.
     *
     */
    session: string;
    /**
     * Required. The resource name of the activity to retrieve. Format:
     * sessions/{session}/activities/{activity} It takes the form
     * sessions/{session}/activities/{activities}.
     *
     */
    activity: string;
  };
  query?: never;
  url: "/sessions/{session}/activities/{activity}";
};

export type GetActivityErrors = {
  /**
   * Invalid argument.
   *
   */
  400: unknown;
  /**
   * Permission denied.
   *
   */
  403: unknown;
  /**
   * Session or activity not found
   *
   */
  404: unknown;
};

export type GetActivityResponses = {
  /**
   * If successful, the response body contains an instance of Activity.
   *
   */
  200: Activity;
};

export type GetActivityResponse =
  GetActivityResponses[keyof GetActivityResponses];

export type ListActivitiesData = {
  body?: never;
  path: {
    /**
     * Required. The parent session, which owns this collection of activities. Format:
     * sessions/{session} It takes the form sessions/{session}.
     *
     */
    session: string;
  };
  query?: {
    /**
     * Optional. The number of activities to return. Must be between 1 and 100, inclusive. If
     * unset, defaults to 50. If set to greater than 100, it will be coerced to 100.
     *
     */
    pageSize?: number;
    /**
     * Optional. A page token, received from a previous activities.list call.
     *
     */
    pageToken?: string;
  };
  url: "/sessions/{session}/activities";
};

export type ListActivitiesErrors = {
  /**
   * Invalid argument.
   *
   */
  400: unknown;
  /**
   * Permission denied.
   *
   */
  403: unknown;
  /**
   * Session not found
   *
   */
  404: unknown;
};

export type ListActivitiesResponses = {
  /**
   * If successful, the response body contains data with the following structure:
   *
   */
  200: {
    /**
     * The activities from the specified session
     *
     */
    activities?: Array<Activity>;
    /**
     * A token, which can be sent as pageToken to retrieve the next page. If this
     * field is omitted, there are no subsequent pages.
     *
     */
    nextPageToken?: string;
  };
};

export type ListActivitiesResponse =
  ListActivitiesResponses[keyof ListActivitiesResponses];

export type GetSourceData = {
  body?: never;
  path: {
    /**
     * Required. The resource name of the source to retrieve. Format: sources/{source} It takes
     * the form sources/{+source}.
     *
     */
    name: string;
  };
  query?: never;
  url: "/sources/{name}";
};

export type GetSourceErrors = {
  /**
   * Invalid argument.
   *
   */
  400: unknown;
  /**
   * Permission denied.
   *
   */
  403: unknown;
  /**
   * Source not found
   *
   */
  404: unknown;
};

export type GetSourceResponses = {
  /**
   * If successful, the response body contains an instance of Source.
   *
   */
  200: Source;
};

export type GetSourceResponse = GetSourceResponses[keyof GetSourceResponses];

export type ListSourcesData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Optional. The filter expression for listing sources, based on AIP-160. If not set, all
     * sources will be returned. Currently only supports filtering by name, which can be used
     * to filter by a single source or multiple sources separated by OR.
     *
     */
    filter?: string;
    /**
     * Optional. The number of sources to return. Must be between 1 and 100, inclusive. If
     * unset, defaults to 30. If set to greater than 100, it will be coerced to 100.
     *
     */
    pageSize?: number;
    /**
     * Optional. A page token, received from a previous sources.list call.
     *
     */
    pageToken?: string;
  };
  url: "/sources";
};

export type ListSourcesErrors = {
  /**
   * Invalid argument.
   *
   */
  400: unknown;
  /**
   * Permission denied.
   *
   */
  403: unknown;
};

export type ListSourcesResponses = {
  /**
   * If successful, the response body contains data with the following structure:
   *
   */
  200: {
    /**
     * The sources from the specified request.
     *
     */
    sources?: Array<Source>;
    /**
     * A token, which can be sent as pageToken to retrieve the next page. If this
     * field is omitted, there are no subsequent pages.
     *
     */
    nextPageToken?: string;
  };
};

export type ListSourcesResponse =
  ListSourcesResponses[keyof ListSourcesResponses];
